skip instead of exit

diff --git a/support/install_packages b/support/install_packages
--- a/support/install_packages
+++ b/support/install_packages
@@ -108,7 +108,6 @@ if (( ${#failed[@]} > 0 )); then
 
     if (( ${#failed[@]} > 0 )); then
         echo "" >&2
-        echo "giving up on: ${failed[*]}" >&2
-        exit 1
+        echo "skipping: ${failed[*]}" >&2
     fi
 fi
